# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [115]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [116]:
A = np.arange(1, 16).reshape(3,5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [117]:
print("dimension =", A.ndim)
print("shape = ", A.shape)
print("size =", A.size)
print("datatype =", A.dtype)


dimension = 2
shape =  (3, 5)
size = 15
datatype = int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [118]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(f"Matrix B:\n{B}\n")
print()
print(f"Matrix C:\n{C}\n")

Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Matrix C:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]



In [119]:
elementwise_subtraction = B - C
print(f"Elementwise Subtraction (B - C):\n{elementwise_subtraction}\n")

elementwise_multiplication = B * C
print(f"Elementwise Multiplication (B * C):\n{elementwise_multiplication}\n")

matrix_multiplication = B @ C
print(f"Matrix Multiplication (B @ C):\n{matrix_multiplication}")

Elementwise Subtraction (B - C):
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise Multiplication (B * C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication (B @ C):
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [120]:
B = np.arange(1, 10).reshape(3, 3)
print(f'Matrix B: \n{B}')

Matrix B: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [121]:
import numpy as np


# Exponentiera varje tal elementvis med np.exp
exp_B = np.exp(B)
print(f'Exponentierad matris B: \n{exp_B}\n')

# Minsta värdet i hela matrisen
min_value = np.min(B)
print(f'Minsta värdet i hela matrisen: {min_value}\n')

# Minsta värdet i varje rad
min_value_row = np.min(B, axis=1)
print(f'Minsta värdet i varje rad: {min_value_row}\n')

# Minsta värdet i varje kolumn
min_value_column = np.min(B, axis=0)
print(f'Minsta värdet i varje kolumn: {min_value_column}\n')

# Indexet för det minsta värdet i hela matrisen
min_index = np.argmin(B)
print(f'Index för det minsta värdet i hela matrisen: {min_index}\n')

# Indexet för det minsta värdet i varje rad
min_index_row = np.argmin(B, axis=1)
print(f'Index för det minsta värdet i varje rad: {min_index_row}\n')

# Summan av alla element
sum_B = np.sum(B)
print(f'Summan av alla element: {sum_B}\n')

# Medelvärdet för varje kolumn
mean_B_column = np.mean(B, axis=0)
print(f'Medelvärdet för varje kolumn: {mean_B_column}\n')

# Medianen för varje kolumn
median_B_column = np.median(B, axis=0)
print(f'Medianen för varje kolumn: {median_B_column}\n')


Exponentierad matris B: 
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minsta värdet i hela matrisen: 1

Minsta värdet i varje rad: [1 4 7]

Minsta värdet i varje kolumn: [1 2 3]

Index för det minsta värdet i hela matrisen: 0

Index för det minsta värdet i varje rad: [0 0 0]

Summan av alla element: 45

Medelvärdet för varje kolumn: [4. 5. 6.]

Medianen för varje kolumn: [4. 5. 6.]



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [122]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [123]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

Vid färre angivna index än det finns axlar kommer de saknade axlarna (saknade index) automatiskt fyllas ut med hela den delen (den eller de dimensioner) som inte specificerats.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [124]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [125]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [126]:
#Iterera elementwise

for i in A.flat:
    print(i)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [127]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


a = np.arange(30) skapare en array från 0 till 29, dvs (30,)

b = a.reshape((2, 3, -1)) omformar array a till en array med tre dimensioner (mot tidigare en dimension). 

Den första siffran (2) anger att jag vill skapa två sk block. 

Den andra siffran (3) anger antalet rader i varje block.

Den tredje siffran (-1) gör att NumPy räknar ut den sista dimensionen baserat på det två övriga dimensionerna och storleken på min array. 

2 block a 3 rader = 6 rader. 30/6 = 5, dvs 5 tal (element) per rad

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [128]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [129]:
import numpy as np
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [130]:
A = np.arange(1, 5).reshape(2, 2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [131]:
import numpy as np

def add_mult_matrices(matrix1, matrix2, operation):

    matrix1 = np.arrange('input tal').reshape()
    matrix2 = np.arrange().reshape()

    # Kontrollera att input är arrays
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise TypeError("Båda matrix måste vara arrays")
    
    # Kontrollera att operationen är korrekt
    if operation not in ['add', 'multiply']:
        raise ValueError("Operation måste vara 'add' eller 'multiply'")
    
    # Lägg till eller multiplicera matrix
    if operation == 'add':
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must have the same dimensions for addition")
        return matrix1 + matrix2
    elif operation == 'multiply':
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Antalet kolumner i den första matrix måste vara samma som antalet rader i den andra matrix")
        return np.dot(matrix1, matrix2)   




### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [132]:
import numpy as np

# UPPGIFT 10.1.1

#Definiera vektorn x enligt nedan. 
x = (4, 3)

# A Vilken dimension har vektorn?

# Svar 1 x 2


In [133]:
# B Beräkna 5x

x = np.array([4, 3])
sum_b = x * 5
print(sum_b)

[20 15]


In [134]:
# C Beräkna 3x
sum_c = x * 3
print(sum_c)


[12  9]


In [135]:
# D Beräkna 5x + 3x
sum_d = (x * 5) +(x * 3)
print(sum_d)

[32 24]


In [136]:
# E Beräkna 8x
sum_e = (x * 8)
print(sum_e)

[32 24]


In [137]:
# F Beräkna 4x - x
sum_f = x * 4 -x
print(sum_f)

[12  9]


In [138]:
# G Beräkna x^T

transposed_vector = x.T
print(transposed_vector)

# Slutsats: Det blir ingen skillnad när man transponerar en endimnesionsvektor i NumPy. Vill man ändå ha 1 kolumn och två rader kan man använda reshape.

reshaped_vector = x.reshape(2, 1)
print(reshaped_vector)


[4 3]
[[4]
 [3]]


H Är x + x^T definierat?

Svar: Nej, om man transponerar x^T så kommer de två vektorerna att ha olika dimensioner.

In [139]:
# I Beräkna ||x|| 

import math
normen = math.sqrt(x[0]**2 + x[1]**2)
print(normen)

# Normen av en vektor x defineras enligt: ||x|| = sqrt(x^Tx)


5.0


# UPPGIFT 10.1.2

Definiera vektor v enligt nedan. 

In [140]:
# A Vilken dimension har vektorn V?
v = np.array([3, 7, 0, 11]).reshape(-1, 1)
print(v)

#Svar: 4 x 1


[[ 3]
 [ 7]
 [ 0]
 [11]]


In [141]:
# B Beräkna 2v
sum_b = v * 2
print(sum_b)

[[ 6]
 [14]
 [ 0]
 [22]]


In [142]:
# C Beräkna 5v + 2v
sum_c = (v * 5) + (v * 2)
print(sum_c)

[[21]
 [49]
 [ 0]
 [77]]


In [143]:
# D Beräkna 4v - 2v
sum_d = (v * 4) - (v * 2)
print(sum_d)

[[ 6]
 [14]
 [ 0]
 [22]]


# E Beräkna V^T, vilken blir den nya dimensionen efter att transponeringen utförts?

Svar: v^T = (3, 7, 0, 11)

In [144]:
# F Beräkna ||v|| 

import math
v = [3, 7, 0, 11]
normen = math.sqrt(v[0]**2 + v[1]**2 + v[2]**2 + v[3]**2)
print(normen)

13.379088160259652


# UPPGIFT 10.1.3

Definiera vektorerna v_1 = [4, 3, 1, 5] och v_2 = [2, 3, 1, 1] 

In [145]:
# A Beräkna ||v_1|| 

import math
v_1 = [4, 3, 1, 5]
normen = math.sqrt(v_1[0]**2 + v_1[1]**2 + v_1[2]**2 + v_1[3]**2)
print(normen)

7.14142842854285


In [146]:
# B Beräkna ||v_1 - v_2|| 

v_1 = np.array([4, 3, 1, 5])  
v_2 = np.array([2, 3, 1, 1])

skillnad = v_1 - v_2  # Subtrahera vektorerna elementvis

normen = np.linalg.norm(skillnad)  # Beräkna normen av skillnaden
print(normen)

#Här använder jag funktionen linalg.norm i NumPy då vektorerna innehåller flertalet variabler.

4.47213595499958


# UPPGIFT 10.2.1
Definiera matriserna. Om det är definierat, utför följande beräkningar


In [147]:
# A (2A)

A = [2, 1, -1, 1, -1, 1]
matris_A = np.array(A).reshape(2, 3)
sum_A = matris_A * 2
print('Matris A =\n', matris_A)
print('Summan =\n', sum_A)


Matris A =
 [[ 2  1 -1]
 [ 1 -1  1]]
Summan =
 [[ 4  2 -2]
 [ 2 -2  2]]


In [148]:
# B (B-SA)
import numpy as np

B = [4, -2, 1, 2, -4, -2]
matris_B = np.array(B).reshape(2, 3)

try:
    matris_A
    matris_B
    if matris_A.shape == matris_B.shape:
        print("Båda matriserna är definierade och har samma form.")
        sum_B = matris_B - 2 * matris_A
        print('Summan =\n', sum_B)
    else:
        print("En eller båda matriserna är definierade, men de har inte samma form.")
except NameError:
    print("En eller båda matriserna är inte definierade.")


Båda matriserna är definierade och har samma form.
Summan =
 [[ 0 -4  3]
 [ 0 -2 -4]]


In [149]:
# C (3C - 2E)

C = [1, 2, 2, 1]
matris_C = np.array(C).reshape(2, 2)

E = [1, 2] 
matris_E = np.array(E).reshape(2, 1)  

try:
    matris_C
    matris_E
    if matris_C.shape == matris_E.shape:
        print("Båda matriserna är definierade och har samma form.")
        
        sum_C = matris_C * 3 - matris_E * 2
        print('Summan =\n', sum_C)
    else:
        print("En eller båda matriserna är definierade, men de har inte samma form.")
except NameError:
    print("En eller båda matriserna är inte definierade.")


En eller båda matriserna är definierade, men de har inte samma form.


In [150]:
# D (2D - 3C)

D = [3, 4, 4, 3]
matris_D = np.array(D).reshape(2, 2)
try:
    matris_D
    matris_C
    if matris_D.shape == matris_C.shape:
        print("Båda matriserna är definierade och har samma form.")
        result = 2 * matris_D - 3 * matris_C
        print('Resultatet av beräkningen (2D - 3C) =\n', result)
    else:
        raise NameError("Dimensionerna matchar inte för matriserna D och C.")
except NameError:
    print("En eller båda matriserna D och C är inte definierade, eller deras dimensioner matchar inte.")




Båda matriserna är definierade och har samma form.
Resultatet av beräkningen (2D - 3C) =
 [[3 2]
 [2 3]]


In [151]:
# E (D^T + 2D)

try:
    matris_D
    transpose_D = matris_D.T
    
    if transpose_D.shape == matris_D.shape:
        print("Båda matriserna är definierade och har samma form.")
        # Beräkningen (D^T + 2D)
        result = transpose_D + 2 * matris_D
        print('Resultatet av beräkningen (D^T + 2D) =\n', result)
    else:
        raise NameError("Dimensionerna matchar inte för matriserna D^T och D.")
except NameError:
    print("Matris D är inte definierad, eller dess dimensioner matchar inte.")


Båda matriserna är definierade och har samma form.
Resultatet av beräkningen (D^T + 2D) =
 [[ 9 12]
 [12  9]]


In [152]:
# F (2C^T - 2D^T)

try:
    matris_C
    matris_D
    transpose_C = matris_C.T
    transpose_D = matris_D.T
    
    if transpose_C.shape == transpose_D.shape:
        print("Båda matriserna är definierade och har samma form.")
        # Beräkningen (2C^T - 2D^T)
        result = 2 * transpose_C - 2 * transpose_D
        print('Resultatet av beräkningen (2C^T - 2D^T) =\n', result)
    else:
        raise NameError("Dimensionerna matchar inte för matriserna C^T och D^T.")
except NameError:
    print("En eller båda matriserna C och D är inte definierade, eller deras dimensioner matchar inte.")

Båda matriserna är definierade och har samma form.
Resultatet av beräkningen (2C^T - 2D^T) =
 [[-4 -4]
 [-4 -4]]


In [153]:
# G (A^T - B)

try:
    matris_A
    matris_B
    transpose_A = matris_A.T
    if transpose_A.shape == matris_B.shape:
        print("Båda matriserna är definierade och har samma form.")
        result = transpose_A - matris_B
        print('Resultatet av beräkningen (A^T - B) =\n', result)
    else:
        raise NameError("Dimensionerna matchar inte för matriserna A^T och B.")
except NameError:
    print("En eller båda matriserna A och B är inte definierade, eller deras dimensioner matchar inte.")

En eller båda matriserna A och B är inte definierade, eller deras dimensioner matchar inte.


In [154]:
# H (AC)

try:
    matris_A
    matris_C
    if matris_A.shape[1] == matris_C.shape[0]:
        print("Båda matriserna är definierade och har samma form.")
        result = np.dot(matris_A, matris_C)
        print('Resultatet av beräkningen (A * C) =\n', result)
    else:
        raise NameError("Dimensionerna matchar inte för att multiplicera matriserna A och C.")
except NameError:
    print("En eller båda matriserna A och C är inte definierade, eller deras dimensioner matchar inte för multiplikation.")


En eller båda matriserna A och C är inte definierade, eller deras dimensioner matchar inte för multiplikation.


In [155]:
# I (CD)

try:
    matris_C
    matris_D
    if matris_C.shape[1] == matris_D.shape[0]:
        print("Båda matriserna är definierade och har samma form.")
        result = np.dot(matris_C, matris_D)
        print('Resultatet av beräkningen (C * D) =\n', result)
    else:
        raise NameError("Dimensionerna matchar inte för att multiplicera matriserna C och D.")
except NameError:
    print("En eller båda matriserna C och D är inte definierade, eller deras dimensioner matchar inte för multiplikation.")


Båda matriserna är definierade och har samma form.
Resultatet av beräkningen (C * D) =
 [[11 10]
 [10 11]]


In [156]:
# J (CB)

try:
    matris_C
    matris_B
    if matris_C.shape[1] == matris_B.shape[0]:
        print("Båda matriserna är definierade och har samma form.")
        result = np.dot(matris_C, matris_B)
        print('Resultatet av beräkningen (C * B) =\n', result)
    else:
        raise NameError("Dimensionerna matchar inte för att multiplicera matriserna C och B.")
except NameError:
    print("En eller båda matriserna C och B är inte definierade, eller deras dimensioner matchar inte för multiplikation.")

Båda matriserna är definierade och har samma form.
Resultatet av beräkningen (C * B) =
 [[  8 -10  -3]
 [ 10  -8   0]]


In [157]:
# K (CI)

try:
    matris_C
    matris_I
    if matris_C.shape[1] == matris_I.shape[0]:
        print("Båda matriserna är definierade och har samma form.")
        result = np.dot(matris_C, matris_I)
        print('Resultatet av beräkningen (C * I) =\n', result)
    else:
        raise NameError("Dimensionerna matchar inte för att multiplicera matriserna C och I.")
except NameError:
    print("En eller båda matriserna C och I är inte definierade, eller deras dimensioner matchar inte för multiplikation.")

En eller båda matriserna C och I är inte definierade, eller deras dimensioner matchar inte för multiplikation.


In [158]:
# L (AB^T)

try:
    matris_A
    matris_B
    transpose_B = matris_B.T
    if matris_A.shape[1] == transpose_B.shape[0]:
        print("Båda matriserna är definierade och har samma form.")
        result = np.dot(matris_A, transpose_B)
        print('Resultatet av beräkningen (A * B^T) =\n', result)
    else:
        raise NameError("Dimensionerna matchar inte för att multiplicera matriserna A och B^T.")
except NameError:
    print("En eller båda matriserna A och B är inte definierade, eller deras dimensioner matchar inte för multiplikation.")


Båda matriserna är definierade och har samma form.
Resultatet av beräkningen (A * B^T) =
 [[5 2]
 [7 4]]


Uppgift 10.2.2 Definera matrinsen

In [159]:
A = [2, 3, 4, 5, 4, 1]
matris_A = np.array(A).reshape(2, 3)

try:
    matris_A
    transpose_A = matris_A.T
    if matris_A.shape[1] == transpose_A.shape[0]:
        print("Båda matriserna är definierade och har samma form.")
        result = np.dot(matris_A, transpose_A)
        print('Resultatet av beräkningen (A * A^T) =\n', result)
    else:
        raise NameError("Dimensionerna matchar inte för att multiplicera matriserna A och A^T.")
except NameError:
    print("Matris A är inte definierad, eller dess dimensioner matchar inte för multiplikation.")

#Beräkna AA^T

Båda matriserna är definierade och har samma form.
Resultatet av beräkningen (A * A^T) =
 [[29 26]
 [26 42]]


Uppgift 10.2.3 Definera matrinserna och verifiera att AB = AC men att B != C

In [160]:
A = [1, 2, 3, 4]
matris_A = np.array(A).reshape(2, 2)

B = [2, 1, 1, 3]
matris_B = np.array(B).reshape(2, 2)

C = [4, 3, 0, 2]
matris_C = np.array(C).reshape(2, 2)

try:
    matris_A
    matris_B
    matris_C
    if matris_A.shape[1] == matris_B.shape[0] and matris_A.shape[1] == matris_C.shape[0]:
        print("Matriserna A, B och C är definierade och har rätt form för multiplikation.")
        AB = np.dot(matris_A, matris_B)
        AC = np.dot(matris_A, matris_C)
        print('Resultatet av beräkningen (A * B) =\n', AB)
        print('Resultatet av beräkningen (A * C) =\n', AC)

        # Verifiera att AB = AC men B != C
        if np.array_equal(AB, AC):
            print("AB är lika med AC.")
        else:
            print("AB är inte lika med AC.")

        if not np.array_equal(matris_B, matris_C):
            print("B är inte lika med C.")
        else:
            print("B är lika med C.")
    else:
        raise NameError("Dimensionerna matchar inte för att multiplicera matriserna A med B eller C.")
except NameError:
    print("En eller flera matriser är inte definierade, eller deras dimensioner matchar inte för multiplikation.")

Matriserna A, B och C är definierade och har rätt form för multiplikation.
Resultatet av beräkningen (A * B) =
 [[ 4  7]
 [10 15]]
Resultatet av beräkningen (A * C) =
 [[ 4  7]
 [12 17]]
AB är inte lika med AC.
B är inte lika med C.


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [161]:
import numpy as np
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)
print(v2.base is v1)
v2[-1] = 123
print(v2)



[0 1 2 3]
[2 3]
True
[  2 123]


In [162]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[  0   1   2 123]


In [163]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
